#description: "<style>.site-footer { display: none !important; }</style>"
theme: jekyll-theme-cayman

# Add this line to stop Jekyll from messing with your Sandcastle files
#exclude:
#  - docs/

# 1. Force Jekyll to safely copy over your Sandcastle folders 
include:
  - docs

# 2. Prevent Jekyll from erasing the docs folder during assembly
keep_files:
  - docs
